version: "3"
services:
  echoip:
    image: ccharon/echoip
    ports:
      - "127.0.0.1:8082:8080"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 128M
        reservations:
          cpus: "0.05"
          memory: 64M
    container_name: echoip
    restart: unless-stopped
    volumes:
      - ./data:/opt/echoip/data:ro
    networks:
      - internal

networks:
  internal: {}
