name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:      
      - uses: actions/checkout@v2
      - name: publish multi-arch docker image
        if: ${{ github.ref == 'refs/heads/master' }}
        run: make docker-pushx
